version: '3.1'

services:
  database:
    image: mysql:latest
    ports:
      - "3307:3307"
    security_opt:
      - seccomp:unconfined
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: root
    volumes:
          - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - 'database:db'
    ports:
        - 8080:80
volumes:
  mysql-data:
